### ISSUE TITLE
Newline in comments breaks the formatting of everything on the page

### ISSUE THREAD

**Issue by anthony-beckett** [makeworld-the-better-one/gemlikes#10]
I used Lagrange, which gives you an option to write multiple lines of text, if you utilise this feature (at least on the [test site](https://portal.mozz.us/gemini/makeworld.space/gemlog/2020-05-21-first.gmi)), the formatting for every single comment breaks.

**Examples**

My entered comment, via the pop-up:
```
username123
Okay this is pretty epic
```

The outcome:
```
Okay (id: 4f3d18cb) @ Sat, 01 Jan 2022 09:33:10 UTC:
this is pretty epic
```

All comments below mine also change like so:
_from_
```
angstyteen (id: 26d71f4c) @ Fri, 10 Dec 2021 17:21:43 UTC:
an edgy comment
```
_to_
```
26d71f4c (id: Fri, 10 Dec 2021 17:21:43 UTC) @ an edgy comment:
username123
```

**Comment by makew0rld** [comment]
Oof. gemlikes was always a bit of a toy, and here you can see how the comment "database" falls apart.

I think this is fixed in 2027038, would you be able to confirm?

**Comment by Mihara** [comment]
Well, I just tried this, and the problem was fixed for me -- linebreaks were excised.

**Comment by makew0rld** [comment]
Ok, I'll close it then. @anthony-beckett let me know if you still have issues and I'll reopen.
